opensky:
  mode: live
  api-url: https://opensky-network.org
  client-id: ${OPENSKY_CLIENT_ID:}
  client-secret: ${OPENSKY_CLIENT_SECRET:}

sqs:
  region: ${AWS_REGION:us-east-1}

aeroapi:
  enabled: true
  base-url: https://aeroapi.flightaware.com/aeroapi
  api-key: ${AEROAPI_KEY:}
