#!/usr/bin/env bash
# Regenerate deploy/k8s/configmaps/*.yaml from the files docker-compose.yml bind-mounts.
#
# Why generated-and-committed rather than a kustomize configMapGenerator: the sources live
# outside deploy/k8s (localstack/, wiremock/, deploy/prometheus, deploy/grafana) and
# `kubectl apply -k` enforces kustomize's load restrictor, which refuses `../` paths.
# scripts/kind-up.sh runs this before every apply, so the committed copies cannot drift;
# `git diff --exit-code deploy/k8s/configmaps` after running it is the drift check.
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
OUT="$REPO_ROOT/deploy/k8s/configmaps"
mkdir -p "$OUT"
cd "$REPO_ROOT"

gen() {
  local name=$1; shift
  {
    echo "# GENERATED by scripts/k8s-gen-configmaps.sh from: $*"
    echo "# Do not edit — change the source file(s) and re-run the script."
    kubectl create configmap "$name" --dry-run=client -o yaml "$@"
  } > "$OUT/$name.yaml"
  echo "wrote $OUT/$name.yaml"
}

# --from-file=<dir> takes every regular file in the directory and skips subdirectories,
# so wiremock/mappings/generated (8.5 MB of gitignored stubs, over the 1 MiB limit) is
# left out on purpose.
gen localstack-init            --from-file=localstack/init-aws.sh
gen wiremock-mappings          --from-file=wiremock/mappings
gen wiremock-files             --from-file=wiremock/__files
gen prometheus-config          --from-file=deploy/prometheus/prometheus.yml
gen grafana-datasources        --from-file=deploy/grafana/provisioning/datasources
gen grafana-dashboard-providers --from-file=deploy/grafana/provisioning/dashboards
gen grafana-dashboards         --from-file=deploy/grafana/dashboards
